### ISSUE TITLE
Document how to have the "Map view" button

### ISSUE THREAD

**Issue by ludovicm67** [ad-freiburg/qlever-ui#102]
I tried to have the "Map view" button on a local instance of the UI, but I wasn't able to have it displayed for queries that returns polygons ; but it's working well on the OSM Planet dataset on the demo instance.

Is it a feature that needs to be configured at the dataset level?
What is the best way to do it?

Is the map already part of the UI, or is there a way to provide a path to use to point to the location where the map is hosted?

**Comment by Qup42** [comment]
The map is a separate project: [adfreiburg/qlever-petrimaps](https://github.com/ad-freiburg/qlever-petrimaps). There currently is no way to configure the "Map view" button for custom datasets. Currently the "Map view" button is shown for some predefined datasets if the last column's datatype is WKT literal. But let's use this issue to collect what you'd need to use it:

- Configuration on a dataset level
  - Enable the "Map view"
  - Set the URL of the map deployment
- Is the heuristic "the last column is of type WKT literal" sufficient for you?

**Comment by ludovicm67** [comment]
@Qup42 Thanks a lot for your anwser here!

Yes, this would be what we would like to see.
Regarding the configuration, it could be great to have it documented somewhere also once it's configurable :)

Regarding the heuristic, it's good enough for now, yes.
In the future, maybe having a way to define the name of a column or so could be great.
If there is a column that have the name that is in the configuration, and if it contains WKT litterals, then it shows the button ; if the column is missing, but if the last one contains some WKT litterals, use that one as fallback, and if not, don't display the button.

**Comment by NicoLaval** [comment]
Thanks @Qup42.

I understand the actual mechanism which makes the button appear or not, but I don't see how we can specify the link of the petrimaps instance when the button appears.

Maybe it's hard coded at the moment in the UI, on a path where you know you deployed the tool on your side?

**Comment by Qup42** [comment]
> Maybe it's hard coded at the moment in the UI, on a path where you know you deployed the tool on your side?

Yes, the path to the petrimaps instance is currently also hard coded.

**Comment by Qup42** [comment]
> Yes, this would be what we would like to see. Regarding the configuration, it could be great to have it documented somewhere also once it's configurable :)

Of course :)

> Regarding the heuristic, it's good enough for now, yes. In the future, maybe having a way to define the name of a column or so could be great. If there is a column that have the name that is in the configuration, and if it contains WKT litterals, then it shows the button ; if the column is missing, but if the last one contains some WKT litterals, use that one as fallback, and if not, don't display the button.

Thanks for the input. I'll add that to the list. Having the data not in the last column unfortunately seems to require a change to the map tool as well.

**Comment by NicoLaval** [comment]
Hi @Qup42,

I hoped updating my data would display the button, but I failed :/

Here is [my Qlever test instance](https://qlever-ign.lab.sspcloud.fr).

When I run the following request, returning object typed as `wktLiteral` as last parameter, button (even with a false link) is not displayed.

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX ign: <http://data.ign.fr/def/geometrie#>
SELECT ?label ?geometry WHERE {
  ?s ign:geometry/geo:asWKT ?geometry .
  ?s rdfs:label ?label .
}
ORDER BY ?label
```

Do you know why?

**Comment by Qup42** [comment]
Your dataset isn't in the (currently hardcoded) set for which the map view is considered. The dataset must be in this predefined set **and** the last column must contain WKT literals.

**Comment by NicoLaval** [comment]
Oh, I hadn't seen this list.

Magic, the button appears :)

Is this filtering useful or is a hack that stuck? Can we delete it?

**Comment by Qup42** [comment]
Looks like a hack that stuck to me, yes. I'd opt for a simple switch per dataset as described [here](https://github.com/ad-freiburg/qlever-ui/issues/102#issuecomment-2363872268). That would make the filter obsolete.
 
I'll try to discuss this internally tomorrow, so that we can move forward with fixing it.
