### ISSUE TITLE
_mapview hack

### ISSUE THREAD

**Issue by NicoLaval** [ad-freiburg/qlever-ui#105]
Select `*_mapview` give petrimaps link in query result table.
Link contains `query` param, which is filling by the object, not a query.

**Comment by Qup42** [comment]
If variables end with the suffix `_query` or `_mapview` all result entries in that column are links to a new query or the map view. The value of that column is used for the new queries. This is not a substitute for the Map view discussed in #102. Does this clear up the question?

**Comment by NicoLaval** [comment]
Sure, I understood it's 2 different things.

But what surprises me is the link built for `?XX_mapview` results: `PETRIMAPS_URL/?query=wkt_literal&mode=objects&backend=...`

Petrimaps is not able to handle this "query", which is not a query but a wkt string object.

Taking [your instance](https://qlever.cs.uni-freiburg.de/osm-planet), with OSM sample, try this query:

```sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>
PREFIX ogc: <http://www.opengis.net/rdf#>
PREFIX osmrel: <https://www.openstreetmap.org/relation/>
SELECT ?osm_id ?hasgeometry_mapview WHERE {
  osmrel:1960198 ogc:sfContains ?osm_id .
  ?osm_id geo:hasGeometry/geo:asWKT ?hasgeometry_mapview .
  ?osm_id osmkey:building ?building .
}
```

Click a `mapview` link in a result row, petrimaps will throw an error.

Maybe `mode=objects` would have to handle this case in petrimaps?

Just to test, I tried a successful trick replacing `PETRIMAPS_URL/?query=wkt_literal&mode=objects&backend=...` by:

```javascript
const query = `SELECT ?geo WHERE {BIND(${wktLiteral} as ?geo)}`;
return `PETRIMAPS_URL/?query=${encodeURI(query)}&mode=objects&backend=...`;
```

And built link is functional in petrimaps ([example](https://qlever.cs.uni-freiburg.de/mapui-petri/?query=SELECT%20%3Fgeo%20WHERE%20%7B%0ABIND%28%22MULTIPOLYGON%28%28%287.8333834%2048.0064493%2C7.8334521%2048.0065004%2C7.8334670%2048.0064915%2C7.8337510%2048.0067028%2C7.8337335%2048.0067134%2C7.8338038%2048.0067658%2C7.8341631%2048.0065485%2C7.8340283%2048.0064481%2C7.8340178%2048.0064545%2C7.8338944%2048.0063627%2C7.8338628%2048.0063392%2C7.8338730%2048.0063330%2C7.8337405%2048.0062345%2C7.8333834%2048.0064493%29%2C%287.8336504%2048.0064600%2C7.8337640%2048.0063887%2C7.8339287%2048.0065109%2C7.8338088%2048.0065794%2C7.8336504%2048.0064600%29%29%29%22%5E%5E%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23wktLiteral%3E%20AS%20%3Fgeo%29%0A%7D&mode=objects&backend=https://qlever.cs.uni-freiburg.de/api/osm-planet))

**Comment by NicoLaval** [comment]
My hacky test is not really clean. We don't need to call API in petrimaps if we already have the object to display.

What do you think about:
- building a link URL with an `object` param instead of `query`, filling it with the wkt literal
- handling this case in petrimaps: if query param is missing, don't call API, if object is present, add directly this one

If you agree, I can try to provide pull requests on qlever-ui & petrimaps

**Comment by Qup42** [comment]
This should now longer be required as of #106 and 9f39f84b9ca07d1276da5928495c6097a87e2b38?

**Comment by NicoLaval** [comment]
Thanks @Qup42.
I close the issue.
