### ISSUE TITLE
Broken example query

### ISSUE THREAD

**Issue by brawer** [ad-freiburg/qlever-ui#44]
In the QLever UI, the bounding box examples are currently broken. (This might well be a backend problem, not an UI issue; sorry if I’m filing this bug at the wrong project). Steps to reproduce:

1. Go to http://qlever.cs.uni-freiburg.de:8080/osm-planet
2. From “Examples”, select “All university buildings in the bounding box of Freiburg”
3. Press “Execute”

Expected: The example query should get processed.
Observed: `Error: Unknown error. Exception: ParseException, cause: Unexpected input: contained(?envelope, "LINESTRING(7.662006 47.903578, 7.930844 48.071058)") }`

**Comment by hannahbast** [comment]
@brawer Sorry for the late reply. The OSM Planet UI has moved to https://qlever.cs.uni-freiburg.de/osm-planet a long time ago and all the queries there should work now. Please let us know if you find a query that doesn't work.
