### ISSUE TITLE
Comments in queries lead to invalid "share" links

### ISSUE THREAD

**Issue by joka921** [ad-freiburg/qlever-ui#46]
Consider for example [this query](https://qlever.cs.uni-freiburg.de/wikidata/z95eV3).

When clicking on "share", the resulting curl links are invalid because the query contains comments whose semantics are "everything until the next newline is a comment" but in the curl requests the (relevant!) newlines are replaced by spaces.

**Comment by hannahbast** [comment]
Just learned that GitHub closes issues automatically when you refer to the issue in the commit message :o Anyway, thanks + I made the same experience earlier today when clicking on @WolfgangFahl's query :-)
