### ISSUE TITLE
Cursor jumps around while typing

### ISSUE THREAD

**Issue by nikkiwd** [ad-freiburg/qlever-ui#57]
I'm not able to write queries in the editor because the cursor frequently jumps around while I'm typing.

One example that I can reproduce in multiple Chrome-based browsers:
* Open https://qlever.cs.uni-freiburg.de/wikidata/ugfCPp
* Press shift+down
* Press delete
* Now try to type anything

What happens: Every key that is pressed causes the cursor to move down a line: Up arrow returns the cursor to the same position, down arrow goes down two lines, ctrl, shift, alt, caps lock move the cursor down one line, shift+down moves the cursor down three lines and doesn't select the text, letter keys insert the letter and then move the cursor down one line.

**Comment by hannahbast** [comment]
@nikkiwd Sorry for the late response. The problem occurs when the `SELECT` is not in all uppercase. This is a bug and we will try to fix it. But at least there is an easy workaround.
