### ISSUE TITLE
New lines sometimes get deleted when moving the cursor immediately afterwards

### ISSUE THREAD

**Issue by nikkiwd** [ad-freiburg/qlever-ui#63]
After pressing enter to add a new line, they often get removed again if I try to leave the line blank and move to a different line.

An example:

* Open https://qlever.cs.uni-freiburg.de/wikidata/PjScET
* Position the cursor at the end of the first line
* Press enter
* Press the up arrow key, or click the end of the first line with the mouse

What happens: The blank line that was just added is removed again

What I'd expect to happen: Blank lines don't get removed unless I delete them

**Comment by hannahbast** [comment]
@nikkiwd OK, I can reproduce this. The thing is that you can move around in a query with TAB, which takes you to the end of the SELECT clause, the end of the query body, and the end of the query. When TAB takes you to the end of the query body, it inserts an empty line, in case you want to add something. If you don't type anything but just press TAB again, the empty line gets deleted again. So it's a feature, not a bug :-)

What is the use case for adding empty lines to the query, then going somewhere else, and then wanting the empty lines to still be there?
