### ISSUE TITLE
Release a Docker image for the arm64 architecture

### ISSUE THREAD

**Issue by ludovicm67** [ad-freiburg/qlever-ui#89]
Right now, the Docker image is only released for the `linux/amd64` architecture.
Would it be possible to get it also for `linux/armd64`?

That way it can run natively on the new Apple CPU (M1, M2, M3…) for example.

**Comment by hannahbast** [comment]
@ludovicm67 The last docker image that I pushed (six days ago), is a multi-arch build (for both `linux/amd64` and `linux/arm64`). Does it work for you? If yes, feel free to close this issue.

**Comment by ludovicm67** [comment]
@hannahbast Thank you for the release of the multi-arch build.
The image is working as expected on arm64 🎉
