### ISSUE TITLE
Allow CSRF_TRUSTED_ORIGINS via env-vars

### ISSUE THREAD

**Issue by vincentjanv** [ad-freiburg/qlever-ui#92]
Hi,

In settings.py; the CSRF_TRUSTED_ORIGINS setting is fixed. In a k8s-setup, we cannot control the hostname (with a Statefulset). Can you change the settings.py so it tries to see if CSRF_TRUSTED_ORIGINS is set as an env-var, if not default to the Freiburg-url?

`CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "https://*.uni-freiburg.de").split(",")
`

**Comment by vincentjanv** [comment]
PR created: https://github.com/ad-freiburg/qlever-ui/pull/93

**Comment by Qup42** [comment]
AFAIK environment variables (and files for secrets) are commonly used for configuration in the k8s world. But I haven't used or applied this anywhere in a project that I work on. So please forgive me if I dig a bit deeper here to understand this myself and also the problem that you face.

1. I assume that you are already mounting a customized `settings_secret.py` somehow. How do you load this?
2. How much it help you being able to set the most important settings (`DEBUG`, `ALLOWED_HOSTS`, `SECRET_KEY`, `CSRF_TRUSTED_ORIGINS` and `DATABASE`) via environment variables?
3. Have you considered using the `DJANGO_SETTINGS_MODULE` environment variable to use a different settings file altogether? You could then load the base `settings.py` there and overwrite the `CSRF_TRUSTED_ORIGINS` there.

Introducing an additional way to configure stuff for a single settings will be confusing. If we use environment variables we should use them consistently for all settings that one might reasonably want to change and use `.env` files etc. If this option is not overwritten, it could also be set from the `settings_secret.py` (although `local_settings.py` would be more fitting then).

**Comment by vincentjanv** [comment]
We are currently setting up Qlever as a additional tool next to Jena Fuseki. I believe my colleague Stan Vertessen was already in contact with you guys.
We have multiple datasets and we need to setup multiple Qlever-servers (one per dataset) and a single Qlever-UI. 
All the qlever-servers and the QLever-ui are accessed via the same URI but with a different path, and Istio (k8s networking) handles the correct forwarding.

Enabling these settings via ENV allows a more semi-production ready environment. Of course we can mount the settings_secret.py with our own values (or even use the suggested code to use the env-vars) but it does seem more user-friendly to allow these options directly.

**Comment by Qup42** [comment]
@hannahbast and I had a meeting yesterday. We understand your need for being able to configure settings via environment variables. #100 allows the customization of basic settings (including the one you needed) with environment variables. All settings can additionally be overwritten using a `settings_local.py`. Please have a look if these changes address your needs.
It is also planned that these basic settings can also be set directly in the Qleverfile.

**Comment by WolfgangFahl** [comment]
I still get Forbidden (403)

CSRF verification failed. Request aborted.
Help

Reason given for failure:

    Origin checking failed - https://qlever.wikidata.dbis.rwth-aachen.de does not match any trusted origins.
    

In general, this can occur when there is a genuine Cross Site Request Forgery, or when [Django’s CSRF mechanism](https://docs.djangoproject.com/en/5.0/ref/csrf/) has not been used correctly. For POST forms, you need to ensure:

    Your browser is accepting cookies.
    The view function passes a request to the template’s [render](https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render) method.
    In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
    If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
    The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.

You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.

it seems the config via yaml file as per #125 is not possible yet.
