### ISSUE TITLE
Automatically release Docker images

### ISSUE THREAD

**Issue by ludovicm67** [ad-freiburg/qlever-ui#96]
It could be great that Docker images are automatically published, similarly to the one in the `qlever` repo.

The architectures that should be supported should at least include:
- linux/amd64
- linux/arm64

That way, it would be easier to try PRs and see the latest changes.

I would also suggest keeping the very simple SQLite DB for now in the image, instead of ignoring it, the time we have a way to create the db on the fly when required (to enable persistency, mounting a volume at a precise path would be the way to go ; if the db file is not present at the start of the container, it should be automatically created).

**Comment by hannahbast** [comment]
Fixed by #98
